[browser]
gatherUsageStats = false

[server]
enableCORS = false
maxUploadSize = 500


[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[ui]
hideTopBar = false
hideSidebarNav = false 