REPLICATE_API_TOKEN = "r8_1kwKxXW2ZWimBmuMyiV7DEWwdN0UwUH3AP2bt"
ANTHROPIC_API_KEY = "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" 
REPLICATE_USERNAME = "pasturl"
[aws]
aws_access_key_id = "AKIAXQX7S7LQMW5TVIU2"
aws_secret_access_key = "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"
region = "eu-central-1"
s3_bucket_name = "ai-shooting"